[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "weather"
dynamic = ["version"]
dependencies = [
  "requests",
]
requires-python = ">= 3"
description = "Fetch weather data"

[tool]
